# Generated by Django 4.2.8 on 2023-12-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salerep',
            fields=[
                ('numdepot', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('nbrarticle', models.IntegerField()),
                ('serveur', models.CharField(blank=True, max_length=20, null=True)),
                ('datedepot', models.DateField()),
                ('timedepot', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'salerep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('numdepot', models.IntegerField()),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('unitprice', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('pricet', models.IntegerField(db_column='priceT')),
                ('date', models.DateField()),
                ('saler', models.CharField(blank=True, max_length=255, null=True)),
                ('tt', models.TimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
    ]
