# Generated by Django 4.2.8 on 2023-12-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Superv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salerep',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'managed': True},
        ),
    ]
