# Generated by Django 4.2.8 on 2023-12-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Superv', '0002_alter_salerep_options_alter_sales_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerep',
            name='timedepot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
